name: MSBuild

on:
  pull_request:
    branches: [ "stable" ]
  workflow_dispatch:
  push:
    branches: [ "stable" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}
      
    - name: Build x86
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x86 ${{env.SOLUTION_FILE_PATH}}
      
    - name: Upload x86 Build Artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: Release-x86
        path: .\Release
        if-no-files-found: error

    - name: Upload x64 Build Artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: Release-x64
        path: .\x64\Release\
        if-no-files-found: error